import React from "react";
import InformationCard from "./InformationCard";
import { faHeartPulse, faTruckMedical, faTooth } from "@fortawesome/free-solid-svg-icons";
import "../Styles/Info.css";

function Info() {
  return (
    <div className="info-section" id="services">
      <div className="info-title-content">
        <h3 className="info-title">
          <span>What We Do</span>
        </h3>
        <p className="info-description">
        CipherRescue utilizes state-of-the-art natural language processing (NLP) techniques and advanced language models to swiftly assess the urgency of each incoming call. This enables the system to prioritize calls effectively and ensure prompt attention to the most critical cases.
        The system intelligently grades each call by analyzing keywords spoken by the caller. By recognizing patterns indicative of urgency, CipherRescue quickly identifies and prioritizes urgent calls for immediate handling.
        CipherRescue ensures data immutability and security by storing call transcripts and other critical information on a blockchain. This decentralized ledger technology guarantees that data remains tamper-proof and accessible only to authorized parties, enhancing trust and transparency in emergency response operations.

        </p>
      </div>

      <div className="info-cards-content">
        <InformationCard
          title="Efficient Call Handling"
          description="The system efficiently handles a large volume of incoming emergency calls, ensuring that no call goes unanswered during critical situations.
          "
          icon={faTruckMedical}
        />

        <InformationCard
          title="Lifesaving Prioritization"
          description=" Through AI-driven analysis, the system determines the criticalness of each emergency, prioritizing responses to ensure zero lives lost by attending to the most urgent cases first.
          "
          icon={faHeartPulse}
        />

        <InformationCard
          title="Reduced Manpower Requirement"
          description="By automating call handling processes, the system significantly reduces the need for human intervention, allowing emergency personnel to focus on critical tasks rather than handling routine calls.
          "
          icon={faTooth}
        />
      </div>
      <div className="info-cards-content">
        <InformationCard
          title="Minimized Waiting Times"
          description="By swiftly parsing caller information and routing calls to the appropriate service providers, the system minimizes waiting times for rescue seekers, ensuring timely assistance during emergencies.

          "
          icon={faTruckMedical}
        />

        <InformationCard
          title="Unified Emergency Number"
          description="  Simplifies the emergency reporting process by providing a single, easy-to-remember number for all types of emergencies, eliminating confusion and streamlining access to essential services"
          icon={faHeartPulse}
        />

        <InformationCard
          title="Data-Driven Decision Making"
          description="Utilizes data analytics and insights generated by the AI model to continually optimize emergency response strategies, improving overall system performance and responsiveness over time."
          icon={faTooth}
        />
      </div>
    </div>
  );
}

export default Info;
